# Generated by Django 4.1.7 on 2023-03-23 20:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_currbal',
        ),
        migrations.AddField(
            model_name='details',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactions',
            name='category',
            field=models.CharField(choices=[('Food', 'Bills'), ('Travel', 'Shopping'), ('HealthCare', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='curbal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.details'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='details',
            name='Today_ex',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='curbal',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='dail_el',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
