# Generated by Django 4.1.7 on 2023-03-23 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0003_details_admin_details_image_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='admin',
        ),
        migrations.AddField(
            model_name='details',
            name='username',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
