# Generated by Django 4.1.7 on 2023-03-24 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_remove_details_dail_el'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='Today_ex',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='details',
            name='curbal',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='curbal',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app1.details'),
            preserve_default=False,
        ),
    ]
